version: "3"

services:
  query_gateway:
    image: subsquid/query-gateway:0.2.0
    environment:
      HTTP_LISTEN_ADDR: 0.0.0.0:8000
      BOOT_NODES: >
        12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58 /dns4/testnet.subsquid.io/tcp/22345,
        12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB /dns4/testnet.subsquid.io/tcp/22346,
        12D3KooWQER7HEpwsvqSzqzaiV36d3Bn6DZrnwEunnzS76pgZkMU /dns4/testnet.subsquid.io/tcp/32345
      RPC_URL: https://sepolia-rollup.arbitrum.io/rpc
      CONFIG_PATH: /app/data/config/gateway-config.yml
      KEY_PATH: /app/data/keys/loadPhaseTwo.key
      ALLOCATIONS_DB_PATH: /app/data/allocations.db
      WALLET_KEY: "${WALLET_PRIVATE_KEY}"
      MULTICALL_CONTRACT_ADDR: 0xcA11bde05977b3631167028862bE2a173976CA11
      WORKER_REGISTRATION_CONTRACT_ADDR: 0x7Bf0B1ee9767eAc70A857cEbb24b83115093477F
      GATEWAY_REGISTRY_CONTRACT_ADDR: 0xC168fD9298141E3a19c624DF5692ABeeb480Fb94
      GATEWAY_CONTRACT_CREATION_BLOCK: 6010034
    volumes:
      - ./query-gateway:/app/data
    ports:
      - "8000:8000"
