version: "3"

services:
  query_gateway:
    image: subsquid/query-gateway:0.2.5
    environment:
      HTTP_LISTEN_ADDR: 0.0.0.0:8000
      BOOT_NODES: >
        12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58 /dns4/testnet.subsquid.io/tcp/22345,
        12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB /dns4/testnet.subsquid.io/tcp/22346,
        12D3KooWQER7HEpwsvqSzqzaiV36d3Bn6DZrnwEunnzS76pgZkMU /dns4/testnet.subsquid.io/tcp/32345
      RPC_URL: https://sepolia-rollup.arbitrum.io/rpc
      CONFIG_PATH: /app/data/config/gateway-config.yml
      KEY_PATH: /app/data/keys/networkTestOneUniformLoad.key
      ALLOCATIONS_DB_PATH: /app/data/allocations.db
      MULTICALL_CONTRACT_ADDR: 0xcA11bde05977b3631167028862bE2a173976CA11
      WORKER_REGISTRATION_CONTRACT_ADDR: 0x7Bf0B1ee9767eAc70A857cEbb24b83115093477F
      NETWORK_CONTROLLER_CONTRACT_ADDR: 0x938026fefC5F2b6d7c1bCC7098A3Fd1A81C2AECF
      GATEWAY_REGISTRY_CONTRACT_ADDR: 0x70FCB652F81436d8f1AFDc9F15085Fb2274281E8
    volumes:
      - ./query-gateway:/app/data
    ports:
      - "8000:8000"
